"""Contract -> DRAFT rules (Gora's rule #1, human-gated).

The LLM drafts rules with clause/page citations. Drafts are validated against the
rule schema and written to rules/draft/. They are NEVER loaded by the engine until a
human reviews them, sets `reviewed_by` and `status: APPROVED`, and moves the file to
rules/approved/.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

from invoice_guard.llm.client import LLMClient, LLMRequest
from invoice_guard.llm.prompts import PromptLibrary
from invoice_guard.models.rules import ContractRule, RuleValidationError
from invoice_guard.tools.extractor import parse_json_object


def draft_rules_for_contract(path: Path, llm: LLMClient, prompts: PromptLibrary, out_dir: Path) -> Path:
    raw = path.read_text("utf-8")
    meta = yaml.safe_load(raw.split("---", 2)[1]) if raw.startswith("---") else {}
    prompt = prompts.get("rule_drafter")
    output = llm.complete(
        LLMRequest(task="draft_rules", system=prompt.text, user=raw[:20000], json_mode=True)
    )
    try:
        candidates = parse_json_object(output).get("rules", [])
    except ValueError:
        candidates = []

    accepted, rejected = [], []
    for candidate in candidates if isinstance(candidates, list) else []:
        try:
            ContractRule.from_dict(candidate)
            accepted.append(candidate)
        except (RuleValidationError, ValueError, TypeError, AttributeError) as exc:
            rejected.append(f"{candidate!r:.120} -> {exc}")

    document = {
        "status": "DRAFT",
        "vendor_id": meta.get("vendor_id"),
        "contract_id": meta.get("contract_id", path.stem),
        "effective_from": str(meta.get("effective_from", date.today().replace(month=1, day=1))),
        "effective_to": str(meta.get("effective_to", date.today().replace(month=12, day=31))),
        "reviewed_by": None,
        "drafted_by": f"llm:{prompt.name}.{prompt.version}",
        "rules": accepted,
    }
    header = (
        "# DRAFT - generated by an LLM. NOT loaded by the rule engine.\n"
        "# To promote: verify every rule against the cited clause, set reviewed_by and\n"
        "# status: APPROVED, then move this file to data/contracts/rules/approved/.\n"
    )
    if rejected:
        header += "# Rejected candidates (failed schema validation):\n" + "".join(
            f"#   - {r}\n" for r in rejected
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{document['contract_id']}.draft.yaml"
    out.write_text(header + yaml.safe_dump(document, sort_keys=False, allow_unicode=True), "utf-8")
    return out
